resolver: lts-12.8
extra-package-dbs: []
packages:
- '.'
- 'tests/test-package/'
flags:
  hsdev:
    docs: False
extra-deps:
- haskell-names-0.9.2
- hformat-0.3.3.0
- simple-log-0.9.6
- text-region-0.3.1.0
ghc-options:
  "$locals": -Wall -fno-warn-tabs
